site_name: SZATech
site_description: Custom precision machining for prototypes, low-volume production and repeat production. SZATech supports research, automation and industrial engineering projects, including complex custom parts.
site_author: SZATech
site_url: https://szatech.com/

use_directory_urls: true

theme:
  name: material
  language: en
  features:
    - navigation.top
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

plugins: []

markdown_extensions:
  - attr_list
  - md_in_html

extra:
  generator: false

copyright: Copyright © SZATech
