# This is a basic workflow to help you get started with Actions

name: Deploy SZATech website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: pip install "mkdocs==1.6.1" "mkdocs-material==9.7.7"

      - name: Build website
        run: mkdocs build --clean

      - name: Publish to GitHub Pages
        run: mkdocs gh-deploy --force --clean
